name: test-solana-contract

on:
  push:
    branches: [main]
    paths:
      - programs/**
      - .github/workflows/test-solana-contract.yml

  pull_request:
    branches: [main]
    paths:
      - programs/**
      - .github/workflows/test-solana-contract.yml

env:
  SOLANA_VERSION: "1.8.10"
  ANCHOR_VERSION: "0.25.0"
  RUST_TOOLCHAIN: nightly-2021-12-23
  CARGO_TERM_COLOR: always

jobs:
  test-solana-contract:
    runs-on: ubuntu-latest
    container: projectserum/build:v0.24.2
    steps:
      - uses: actions/checkout@v3

      - name: Use node@16.x
        uses: actions/setup-node@v3.3.0
        with:
          node-version: 16.x

      - run: corepack enable

      - uses: pnpm/action-setup@v2.2.2
        with:
          version: 7.3.0
          run_install: false

      - name: List rustup toolchains
        run: rustup toolchain list
      - name: Set default toolchain
        run: rustup default stable

      - name: Generate new keygen
        run: solana-keygen new -o ./config/id.json
      - name: Set solana target cluster to local
        run: solana config set --url http:localhost:8899
      - name: Check solana config
        run: solana config get

      - name: Install dependencies
        run: pnpm install

      - name: Run build script
        run: pnpm run build
      - name: Run test script
        run: pnpm run test
